version: '3'

services:  
  # mysql database
  db:
    container_name: mysql_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - config/mysql.env
    volumes:
      - db-data-volume:/var/lib/mysql

  # django web server
  web:
    build: "./subsystem2"
    container_name: subsystem2
    command: bash -c "./wait-for-it.sh db:3306 --
      python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    ports:
      - "9000:9000"
    depends_on:
      - db
  
  # nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  db-data-volume: