version: '3'

services:
  # mysql database
  db:
    container_name: mysql_db
    restart: always
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./config/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - db-data-volume:/var/lib/mysql

  # minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    command: server /data
    env_file:
      - ./config/minio.env

  # django web server
  web:
    build: "./subsystem2"
    container_name: subsystem2
    command: bash -c "./wait-for-it.sh -t 0 db:3306 --
      python manage.py makemigrations --merge --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - ./config/minio.env
      - ./config/mysql.env
    environment:
      - DJANGO_SETTINGS_MODULE=subsystem2.settings.local

  # nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./subsystem2:/code
    depends_on:
      - web

volumes:
  db-data-volume:
