version: '3'

services:  
  # postgres database
  db:
    build: "./db"

  # django web server
  subsystem2:
    build: "./subsystem2"
    container_name: subsystem2
    command: bash -c "./wait-for-it.sh db:3306 --
      python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    ports:
      - "9000:9000"
    depends_on:
      - db
