# Generated by Django 2.1.1 on 2018-09-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Image'), (0, 'BP Record'), (4, 'Document'), (3, 'Moive'), (2, 'Time-series Record')], default=0)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(verbose_name='created on')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthDataPermission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_access', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name='last updated on')),
                ('health_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.HealthData')),
                ('patients', models.ManyToManyField(to='webapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='IsAPatientOf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('has_read_access', models.BooleanField(default=True)),
                ('has_write_access', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'therapist'), (0, 'patient'), (2, 'researcher')], default=0)),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('policy', models.IntegerField(choices=[(0, 'Read Only'), (1, 'Read/Write')], default=1)),
                ('patients', models.ManyToManyField(to='webapp.Patient')),
            ],
        ),
        migrations.RenameModel(
            old_name='Visit_Record',
            new_name='VisitRecord',
        ),
        migrations.RemoveField(
            model_name='has_consent_from_patient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='has_consent_from_patient',
            name='researcher',
        ),
        migrations.RemoveField(
            model_name='health_data',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='health_data_permission',
            name='health_data',
        ),
        migrations.RemoveField(
            model_name='health_data_permission',
            name='therapist',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='patients',
        ),
        migrations.DeleteModel(
            name='Has_Consent_From_Patient',
        ),
        migrations.DeleteModel(
            name='Health_Data',
        ),
        migrations.DeleteModel(
            name='Health_Data_Permission',
        ),
        migrations.AddField(
            model_name='ward',
            name='therapists',
            field=models.ManyToManyField(to='webapp.Therapist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='therapist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Therapist'),
        ),
        migrations.AddField(
            model_name='isapatientof',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Therapist'),
        ),
    ]
