# Generated by Django 2.1.1 on 2018-09-30 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20180930_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Time-series Record'), (0, 'BP Record'), (3, 'Moive'), (4, 'Document')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(2, 'researcher'), (1, 'therapist'), (0, 'patient')], default=0),
        ),
    ]
