# Generated by Django 2.1.1 on 2018-09-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_allow_blank_in_userprofile_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='therapist',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.Therapist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='type',
            field=models.IntegerField(choices=[(1, 'Image'), (2, 'Time-series Record'), (0, 'BP Record'), (4, 'Document'), (3, 'Moive')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(2, 'researcher'), (1, 'therapist'), (0, 'patient')], default=0),
        ),
        migrations.AlterField(
            model_name='ward',
            name='policy',
            field=models.IntegerField(choices=[(1, 'Read/Write'), (0, 'Read Only')], default=1),
        ),
    ]
