# Generated by Django 2.1.1 on 2018-10-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181004_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='minio_filename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdatapermission',
            name='permission',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')]),
        ),
        migrations.AlterField(
            model_name='isapatientof',
            name='document_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='isapatientof',
            name='image_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='isapatientof',
            name='movie_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='isapatientof',
            name='timeseries_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='document_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='image_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='movie_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
        migrations.AlterField(
            model_name='ward',
            name='timeseries_access',
            field=models.IntegerField(choices=[(0, 'No Access'), (1, 'Read Only'), (2, 'Write Only'), (3, 'Read / Write')], default=1),
        ),
    ]
