# Generated by Django 2.1.1 on 2018-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_add_ble_token_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bleotpdevice',
            options={'verbose_name': 'BLE OTP Device', 'verbose_name_plural': 'BLE OTP Devices'},
        ),
        migrations.RenameField(
            model_name='healthdata',
            old_name='therapist',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='healthdatapermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='isapatientof',
            name='document_access',
        ),
        migrations.RemoveField(
            model_name='isapatientof',
            name='image_access',
        ),
        migrations.RemoveField(
            model_name='isapatientof',
            name='movie_access',
        ),
        migrations.RemoveField(
            model_name='isapatientof',
            name='timeseries_access',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='document_access',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='image_access',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='movie_access',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='timeseries_access',
        ),
        migrations.AddField(
            model_name='healthdatapermission',
            name='read_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='isapatientof',
            name='read_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='read_access',
            field=models.BooleanField(default=True),
        ),
    ]
