# Generated by Django 2.1.1 on 2018-10-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_update-permission-design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='sex',
        ),
    ]
