# Generated by Django 2.1.1 on 2018-10-23 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_update-permission-design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='creator',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Therapist'),
        ),
    ]
