# Generated by Django 2.1.1 on 2018-10-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_merge_20181024_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Researcher'),
        ),
    ]
