# Generated by Django 2.1.1 on 2018-10-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_userprofile_researcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bloodtype',
            field=models.CharField(choices=[('ON', 'O-'), ('OP', 'O+'), ('AN', 'A-'), ('AP', 'A+'), ('BN', 'B-'), ('BP', 'B+'), ('ABN', 'AB-'), ('ABP', 'AB+')], default='AP', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('CHINESE', 'Chinese'), ('MALAY', 'Malay'), ('INDIAN', 'Indian'), ('CAUCASIAN', 'Caucasian'), ('OTHER', 'Other')], default='Chinese', max_length=100),
            preserve_default=False,
        ),
    ]
