# Generated by Django 2.1.1 on 2018-11-01 15:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_userprofile_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
