# Generated by Django 2.1.1 on 2018-11-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_add_richtextfield'),
        ('webapp', '0014_auto_20181031_1633'),
    ]

    operations = [
    ]
