# Generated by Django 2.1.1 on 2018-11-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20181031_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'Image'), (1, 'Time Series'), (2, 'Movie'), (3, 'Document'), (4, 'Diagnosis'), (5, 'Blood Pressure Reading'), (6, 'Height Reading'), (7, 'Weight Reading')], default=0),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='description',
            field=models.CharField(max_length=4000),
        ),
    ]
