# Generated by Django 2.1.1 on 2018-11-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_merge_20181101_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='data_type',
            field=models.IntegerField(choices=[(0, 'Image'), (1, 'Time Series'), (2, 'Movie'), (3, 'Document'), (4, 'Others')], default=0),
        ),
    ]
