# Generated by Django 2.1.1 on 2018-11-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20181102_0148'),
        ('webapp', '0017_auto_20181102_0544'),
    ]

    operations = [
    ]
