# Generated by Django 2.1.1 on 2018-11-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_add_sign_device_to_hehealthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None),
        ),
    ]
