# Generated by Django 2.1.1 on 2018-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_add_sig_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='is_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
